Repository prathimacode-hub/Treksy, pull requests merged in 2022-02, with the labels that each got.

#14 header component added
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  styles.css
Labels: JWOC, easy

#16 Added Footer And Font awesome CDN
  index.html
Labels: JWOC, easy, Approved

#18 Folder structure added + cleaned up some code
  about-page/about.html
  assets/img/plan.jpg
  assets/img/travel.jpg
  css/about.css
  index.html
  pages/about.html
  script.js
Labels: JWOC, easy, Approved

#28 Setup React project inside treksy-react-app
  React App/README.md
  treksy-react-app/.gitignore
  treksy-react-app/README.md
  treksy-react-app/package-lock.json
  treksy-react-app/package.json
  treksy-react-app/public/favicon.ico
  treksy-react-app/public/index.html
  treksy-react-app/public/logo192.png
  treksy-react-app/public/logo512.png
  treksy-react-app/public/manifest.json
  treksy-react-app/public/robots.txt
  treksy-react-app/src/App.css
  treksy-react-app/src/App.js
  treksy-react-app/src/App.test.js
  treksy-react-app/src/index.css
  treksy-react-app/src/index.js
  treksy-react-app/src/logo.svg
  treksy-react-app/src/reportWebVitals.js
  treksy-react-app/src/setupTests.js
Labels: JWOC, Approved

#29 Added login and register components
  treksy-react-app/package-lock.json
  treksy-react-app/package.json
  treksy-react-app/public/index.html
  treksy-react-app/src/App.js
  treksy-react-app/src/assets/pictures/user0.jpg
  treksy-react-app/src/pages/user/UserLogin.js
  treksy-react-app/src/pages/user/UserRegister.js
  treksy-react-app/src/styles/UserLogin.css
  treksy-react-app/src/styles/UserRegister.css
Labels: JWOC, medium, Approved

#38 Trip Planner Issue #6
  .vscode/settings.json
  assets/img/trip planner img/image1.jpeg
  assets/img/trip planner img/image2.jpeg
  assets/img/trip planner img/image3.jpeg
  assets/img/trip planner img/image4.jpg
  css/trip planner.css
  js/trip planner.js
  pages/trip planner.html
Labels: JWOC, easy, Approved

#40 Navbar and carousel added to react version of the website
  treksy-react-app/package-lock.json
  treksy-react-app/package.json
  treksy-react-app/public/index.html
  treksy-react-app/src/App.js
  treksy-react-app/src/assets/pictures/carousel-img/img1.jfif
  treksy-react-app/src/assets/pictures/carousel-img/img2.jfif
  treksy-react-app/src/assets/pictures/carousel-img/img3.jfif
  treksy-react-app/src/components/Header.js
  treksy-react-app/src/pages/Home.js
  treksy-react-app/src/styles/Header.css
Labels: JWOC, Approved

#46 Hamburger
  index.html
  styles.css
Labels: JWOC, easy, Approved

#48 added contact.html backend with hCaptcha
  .gitignore
  css/contact.css
  js/contact.js
  pages/contact.html
Labels: Approved

#43 Section + Footer added
  treksy-react-app/public/index.html
  treksy-react-app/src/components/Footer.js
  treksy-react-app/src/components/Header.js
  treksy-react-app/src/components/Section.js
  treksy-react-app/src/pages/Home.js
  treksy-react-app/src/styles/Footer.css
  treksy-react-app/src/styles/Header.css
  treksy-react-app/src/styles/Sections.css
Labels: JWOC, medium, Approved

#49 Adding navbar and footer to all other pages issue #35
  css/about.css
  css/contact.css
  css/trip planner.css
  pages/about.html
  pages/contact.html
  pages/trip planner.html
Labels: JWOC, medium, Approved

#51 added booking page
  css/booking.css
  index.html
  pages/booking.html
Labels: JWOC, medium, Approved

#47 Map Popup not working in footer (mobile view) #45
  index.html
  script.js
  styles.css
Labels: JWOC, easy, Approved

#30 Added new fonts, and updated UI
  .deepsource.toml
  css/about.css
  css/contact.css
Labels: JWOC, easy, Approved
